#!/bin/sh

export GOPATH=`pwd`/Godeps/_workspace:$GOPATH

curl -sL https://github.com/upfluence/etcdenv/releases/download/v0.3.3/etcdenv-linux-amd64-0.3.3 \
  > etcdenv

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o fleet-ship

docker build -t upfluence/fleet-ship:latest .
docker push upfluence/fleet-ship:latest
